# Generated by Django 4.1.7 on 2023-04-04 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
